version: "3.7"

services:
  fe:
    build: ./visualization
    ports:
      - "3000:3000"
    volumes:
      - ./visualization:/etc/app
    stdin_open: true
    tty: true
    networks:
      - efk

  fluentd:
    build: efk/images/fluent
    ports:
      - "24224:24224"
      - "9880:9880"
    volumes:
      - ./efk/images/fluent/fluent.conf:/fluentd/etc/fluent.conf
    networks:
      - efk

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - efk

  elasticsearch-mapping-init:
    build: ./efk/images/elastic-init
    links:
      - elastic
    depends_on:
      - elastic
    networks:
      - efk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    volumes:
      - ./efk/images/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - efk
    ports:
      - "5601:5601"

volumes:
  elastic-data:
  fe_node_modules:

networks:
  efk:


