version: "3.7"

services:
  fluentd:
    build: images/fluent
    ports:
      - "24224:24224"
      - "9880:9880"
    volumes:
      - ./images/fluent/fluent.conf:/fluentd/etc/fluent.conf
    networks: 
      - efk

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - efk

volumes:
  elastic-data:

networks:
  efk: